### ISSUE TITLE
Auto Focus

### ISSUE THREAD

**Issue by stefanbrunner** [philipptrenz/photo-booth#128]
The people are newer at the same place in front of the camera. But the auto focus takes cuple of seconds over the countdown. Does anyone have an idea how to give the autofocus command to the camera when the countdown starts?

thanks for any advise

**Comment by philipptrenz** [comment]
Hey Stefan,

Unfortunately this is a technical limitation. The gphoto2 library is only capable to trigger photos. When the trigger command gets executed, the camera will perform the capturing autonomously. Adjusting the focus takes time and depends on many factors, like camera model, environmental lighting, camera scene etc.

What you can do is trying to optimize your scene, so that your camera can focus faster:

* Make sure your scene is bright enough
* Make sure your AF light on the camera is not covered 
* There are also camera flashes that have an additional AF light, which can also improve the AF speed (I have an Metz mecablitz 52 AF-1)

Hope that helps you out!
