### ISSUE TITLE
Error when saving photo

### ISSUE THREAD

**Issue by jasonumd** [philipptrenz/photo-booth#25]
After getting through the issue 22 that was solved today, I sometimes and able to transfer photos, but mostly I get "Whoops ... Something went wrong when saving the photo, please try again". Using a Nikon D5200.

**Comment by philipptrenz** [comment]
When saving the images fails its most likely a problem with the user rights of the `content` folder and  subfolders. I ran into the same problem by starting photo-booth sometimes with and sometimes without `sudo`. When photo-booth runs as root all the folders get created with root privileges so that when running afterwards as normal user there is no writing authorization.

May this be the case for your issue?

**Comment by jasonumd** [comment]
That sounds like it could be it. In issue 22, you said to issue the following commands:

npm start
sudo npm start
node scripts/cli.js

How do I issue them in succession? Once I enter the first, I can't enter another?

**Comment by philipptrenz** [comment]
They were just for testing purposes under different scenarios.

Easiest way for you is to delete the `content` folder and then just following the regular instructions:
https://github.com/philipptrenz/photo-booth#run-photo-booth
