### ISSUE TITLE
Showing camera input on countdown

### ISSUE THREAD

**Issue by seegermattijs** [philipptrenz/photo-booth#26]
It would be nice to view the camera input with the countdown on top of the screen. 
Is this possible?

**Comment by philipptrenz** [comment]
Hey,
gphoto2 supports a live preview for very few cameras. Since my goal is to keep the software compatible with as many cameras as possible, I will not implement that feature.
But please feel free to implement this feature, if it is optional and does not conflict with cameras not supporting this gphoto2 feature I will integrate it.

**Comment by timetolapse** [comment]
Has someone a sample soltion or any hint how to make it available?
I can't find a good solution.
