### ISSUE TITLE
Hardware Acceleration renders official Raspberry DSI Display black

### ISSUE THREAD

**Issue by Knochi** [philipptrenz/photo-booth#48]
After reboot the display shows the multicolor square and then black screen (backlight is active).

When last line is commented out everthing works as expected.
[config.txt](https://github.com/philipptrenz/photo-booth/files/2533450/config.txt)

**Comment by philipptrenz** [comment]
Which version of Raspberry Pi do you use? Anyways, this should not be a photo-booth related issue.

**Comment by Knochi** [comment]
Raspberry Pi 3 B

**Comment by philipptrenz** [comment]
Okay. But as the issue is not photo-booth related I ask you to consult relevant forums on Raspberry Pi regarding its hardware acceleration (i.e. https://www.raspberrypi.org/forums/). I'm pretty sure you are not the first one with this issue ;)

**Comment by Knochi** [comment]
OK.. a quick google search didn't give any reasonable results. But will Photo-Booth run without GPU acceleration as well? I'm still waiting for the camera cable so I can't try it out right now.

**Comment by philipptrenz** [comment]
The performance is better with enabled hardware acceleration, but photo-booth also runs without. 

You could also just try to re-write the image to the SD card. I experienced strange behavior on Raspberry Pi’s which seemed to be caused by corrupted images several times. Check the hash after downloading the image and use a burn tool with validation like [etcher](https://www.balena.io/etcher/)
