### ISSUE TITLE
Configure dnsmasq

### ISSUE THREAD

**Issue by alopezbu** [philipptrenz/photo-booth#85]
Hi @philipptrenz first of all thank you very much for your work. I would like to know how have you configurate your dnsmasq to connect with the webapp through "photo.app" instead of your IP.

Thank you.

**Comment by philipptrenz** [comment]
_I used the following steps in Raspbian Stretch:_ 

## Network configuration

### Install all the required software in one go with this command:

```bash
sudo apt-get install dnsmasq hostapd
```

Stop the services to apply configuration changes:

```bash
sudo systemctl stop dnsmasq && sudo systemctl stop hostapd
```

### Configuring a static IP

We are configuring a standalone network to act as a server, so the Raspberry Pi needs to have a static IP address assigned to the wireless interface. This documentation assumes that we are using the `192.168.5.1/24` address range for our wireless network, so we will assign the server the IP address `192.168.5.1`. It is also assumes that the wireless interface is `wlan0`.

To configure the static IP, edit the dhcpcd configuration file with:

```bash
sudo nano /etc/dhcpcd.conf
```

Go to the end of the file and edit it, so that it looks like the following:

```bash
interface wlan0
static ip_address=192.168.5.1/24
```

Now restart the dhcpcd daemon:

```bash
sudo service dhcpcd restart
```

### Configuring the DHCP server (dnsmasq)

The DHCP service is provided by dnsmasq. By default, the configuration file contains a lot of information that is not needed, and it is easier to start from scratch. Rename the existing configuration file and edit a new one:

```bash
sudo mv /etc/dnsmasq.conf /etc/dnsmasq.conf.orig  
sudo nano /etc/dnsmasq.conf
```

Copy the following into the dnsmasq configuration file and save it:

```shell
######### interface ########
interface=wlan0      # Your network interface, usually wlan0

######### dns ########
# Never forward plain names (without a dot or domain part)
domain-needed
# Never forward addresses in the non-routed address spaces
bogus-priv
# dont read resolv.conf,  use the defined servers instead
no-resolv
server=8.8.8.8
server=8.8.4.4

######### dhcp ##########
# Add local-only domains here, queries in these domains are answered
# from /etc/hosts or DHCP only
local=/home/
# Set this (and domain: see below) if you want to have a domain
# automatically added to simple names in a hosts-file.
expand-hosts
# adds my local domain to each dhcp host
domain=home
# my private dhcp range + subnetmask + 24h lease time
dhcp-range=192.168.5.10,192.168.5.60,255.255.255.0,24h
# set route to my local network gateway, which is the Pi itself
dhcp-option=option:router,192.168.5.1

#windows 7 float fix
#http://brielle.sosdg.org/archives/522-Windows-7-flooding-DHCP-server-with-DHCP$
dhcp-option=252,"\n"

###### logging ############
# own logfile
log-facility=/var/log/dnsmasq.log
log-async
# log dhcp infos
log-dhcp
# debugging dns
#log-queries
```

So for wlan0, we are going to provide IP addresses between 192.168.5.10 and 192.168.5.60, with a lease time of 24 hours.

### Configure the DNS entry for `photo.app`

```bash
sudo nano /etc/hosts
```

add the following line at the top:

```bash
192.168.5.1     photo.app       photo.booth     photo-booth
```


### Configuring the access point host software (hostapd)

You need to edit the hostapd configuration file, located at /etc/hostapd/hostapd.conf, to add the various parameters for your wireless network. After initial install, this will be a new/empty file.

```bash
sudo nano /etc/hostapd/hostapd.conf
```

Add the information below to the configuration file. This configuration assumes we are using channel 7, with a network name of NameOfNetwork, and a password AardvarkBadgerHedgehog. Note that the name and password should not have quotes around them. The passphrase should be between 8 and 64 characters in length.

```bash
interface=wlan0
driver=nl80211
ssid=photo-booth
hw_mode=g
channel=7
wmm_enabled=0
macaddr_acl=0
auth_algs=1
```

We now need to tell the system where to find this configuration file.

```bash
sudo nano /etc/default/hostapd
```

Find the line with #DAEMON_CONF, and replace it with this:

```bash
DAEMON_CONF="/etc/hostapd/hostapd.conf"
```

### Start it up

Now start up the remaining services:

```bash
sudo systemctl start hostapd
sudo systemctl start dnsmasq
```


## Redirect DNS of "photo.app" to 192.168.5.1

```bash
sudo nano /etc/dnsmasq.conf
```

add

```bash
# Redirect everything to photo-booth
address=/#/192.168.5.1
```
